version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - mvn package
      - echo Post-Build completed on `date`
artifacts:
  files:
    - target/fluxnews-api-0.0.1-SNAPSHOT.war
    #- .ebextensions/**/*
  base-directory: 'target/fluxnews-api-0.0.1-SNAPSHOT.war'